def get_advance_to_mannequin_mapping():
    """
    Advanced Skeleton 조인트 이름을 언리얼 엔진 마네퀸 스켈레톤 이름으로 매핑하는 딕셔너리 반환
    
    Returns:
        dict: Advanced Skeleton 조인트 이름 -> 언리얼 마네퀸 이름 매핑
    """
    advance_to_mannequin_mapping = {'Root_M': 'pelvis',
                                    'Spine1_M': 'spine_01',
                                    'Spine2_M': 'spine_02',
                                    'Spine3_M': 'spine_03',
                                    'Spine4_M': 'spine_04',
                                    'Chest_M': 'spine_05',
                                    'Neck1_M': 'neck01',
                                    'Neck2_M': 'neck01',
                                    'Head_M': 'head',
                                    'Scapula_L': 'clavicle_l',
                                    'Shoulder_L': 'upperarm_l',
                                    'ShoulderPart1_L': 'upperarm_twist_01_l',
                                    'ShoulderPart2_L': 'upperarm_twist_01_l',
                                    'Elbow_L': 'lowerarm_l',
                                    'ElbowPart1_L': 'lowerarm_twist_02_l',
                                    'ElbowPart2_L': 'lowerarm_twist_01_l',
                                    'Wrist_L': 'hand_l',
                                    'ThumbFinger1_L': 'thumb_01_l',
                                    'ThumbFinger2_L': 'thumb_02_l',
                                    'ThumbFinger3_L': 'thumb_03_l',
                                    'IndexFinger0_L': 'index_metacarpal_l',
                                    'IndexFinger1_L': 'index_01_l',
                                    'IndexFinger2_L': 'index_02_l',
                                    'IndexFinger3_L': 'index_03_l',
                                    'MiddleFinger0_L': 'middle_metacarpal_l',    
                                    'MiddleFinger1_L': 'middle_01_l',
                                    'MiddleFinger2_L': 'middle_02_l',
                                    'MiddleFinger3_L': 'middle_03_l',
                                    'RingFinger0_L': 'ring_metacarpal_l',
                                    'RingFinger1_L': 'ring_01_l',
                                    'RingFinger2_L': 'ring_02_l',
                                    'RingFinger3_L': 'ring_03_l',
                                    'PinkyFinger0_L': 'pinky_metacarpal_l',
                                    'PinkyFinger1_L': 'pinky_01_l',
                                    'PinkyFinger2_L': 'pinky_02_l',
                                    'PinkyFinger3_L': 'pinky_03_l',
                                    'Scapula_R': 'clavicle_r',
                                    'Shoulder_R': 'upperarm_r',
                                    'ShoulderPart1_R': 'upperarm_twist_01_r',
                                    'ShoulderPart2_R': 'upperarm_twist_01_r',
                                    'Elbow_R': 'lowerarm_r',
                                    'ElbowPart1_R': 'lowerarm_twist_02_r',
                                    'ElbowPart2_R': 'lowerarm_twist_01_r',
                                    'Wrist_R': 'hand_r',
                                    'ThumbFinger1_R': 'thumb_01_r',
                                    'ThumbFinger2_R': 'thumb_02_r',
                                    'ThumbFinger3_R': 'thumb_03_r',
                                    'IndexFinger0_R': 'index_metacarpal_r',
                                    'IndexFinger1_R': 'index_01_r',
                                    'IndexFinger2_R': 'index_02_r',
                                    'IndexFinger3_R': 'index_03_r',
                                    'MiddleFinger0_R': 'middle_metacarpal_r',
                                    'MiddleFinger1_R': 'middle_01_r',
                                    'MiddleFinger2_R': 'middle_02_r',
                                    'MiddleFinger3_R': 'middle_03_r',
                                    'RingFinger0_R': 'ring_metacarpal_r',
                                    'RingFinger1_R': 'ring_01_r',
                                    'RingFinger2_R': 'ring_02_r',
                                    'RingFinger3_R': 'ring_03_r',
                                    'PinkyFinger0_R': 'pinky_metacarpal_r',
                                    'PinkyFinger1_R': 'pinky_01_r',
                                    'PinkyFinger2_R': 'pinky_02_r',
                                    'PinkyFinger3_R': 'pinky_03_r',
                                    'Hip_L': 'thigh_l',
                                    'HipPart1_L': 'thigh_twist_01_l',
                                    'HipPart2_L': 'thigh_twist_02_l',
                                    'Knee_L': 'calf_l',
                                    'KneePart1_L': 'calf_twist_02_l',
                                    'KneePart2_L': 'calf_twist_01_l',
                                    'Ankle_L': 'foot_l',
                                    'Toes_L': 'toe_l',
                                    'Hip_R': 'thigh_r',
                                    'HipPart1_R': 'thigh_twist_01_r',
                                    'HipPart2_R': 'thigh_twist_02_r',
                                    'Knee_R': 'calf_r',
                                    'KneePart1_R': 'calf_twist_02_r',
                                    'KneePart2_R': 'calf_twist_01_r',
                                    'Ankle_R': 'foot_r',
                                    'Toes_R': 'toe_r'}
    
    return advance_to_mannequin_mapping
